version: '4'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=080425
      - POSTGRES_DB=dcasistance
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build: ./
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY=9IHDh9V/2GhxxdmrJNpsHhx2L1A2+dW4I2S9PL21UjVvcaOHpjMAaGbae+aMoe7YK8xKuPpx37pwXH+eb80JWorjAZNxk/rnLyS4m31eDSZgvzkp72fufNzhocbQCVkEgZMk5m4FiWySy+7jzDbeKuuMcM6nsc43vvzkVS9ULF+essC8c38rbDjGtTOv15Q1aht8bsJ8Wmqw7qhS0J6GFS+5IZVfxlmDhrQZsf0ZKEMTVl5xvrMyNMbnWVQT7W+iMera63l9E7vWdHJZF41j+Vq19hgQPJyARZ89jrKWcRNbWUihQwtPpZIhNdlJSE7Am6Q0kcx4Pk6/XV4ZP7Kogw==
      - DATABASE_URL=postgresql://postgres:080425@localhost:5432/dcassistance
    depends_on:
      - postgres 
volumes:
  postgres: