-- CreateTable
CREATE TABLE "Users" (
    "user_id" SERIAL NOT NULL,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "level" TEXT NOT NULL,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "create_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Users_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "Teams" (
    "team_id" SERIAL NOT NULL,
    "team_name" TEXT NOT NULL,

    CONSTRAINT "Teams_pkey" PRIMARY KEY ("team_id")
);

-- CreateTable
CREATE TABLE "Company" (
    "comp_id" SERIAL NOT NULL,
    "team_id" INTEGER NOT NULL,
    "team_name" TEXT NOT NULL,

    CONSTRAINT "Company_pkey" PRIMARY KEY ("comp_id")
);

-- CreateTable
CREATE TABLE "Members" (
    "member_id" SERIAL NOT NULL,
    "comp_id" INTEGER NOT NULL,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "dateOfSign" TIMESTAMP(3) NOT NULL,
    "create_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Members_pkey" PRIMARY KEY ("member_id")
);

-- CreateTable
CREATE TABLE "ChecklistPhase1" (
    "id" SERIAL NOT NULL,
    "main_meter" DOUBLE PRECISION NOT NULL,
    "atsphase1" BOOLEAN NOT NULL,
    "atsphase1_l1" DOUBLE PRECISION NOT NULL,
    "atsphase1_l2" DOUBLE PRECISION NOT NULL,
    "atsphase1_l3" DOUBLE PRECISION NOT NULL,
    "atsphase1_i1" DOUBLE PRECISION NOT NULL,
    "atsphase1_i2" DOUBLE PRECISION NOT NULL,
    "atsphase1_i3" DOUBLE PRECISION NOT NULL,
    "atsphase1_power" DOUBLE PRECISION NOT NULL,
    "atsphase1_meter" DOUBLE PRECISION NOT NULL,
    "atsphase1_in" DOUBLE PRECISION NOT NULL,
    "emdb" BOOLEAN NOT NULL,
    "emdb_l1" DOUBLE PRECISION NOT NULL,
    "emdb_l2" DOUBLE PRECISION NOT NULL,
    "emdb_l3" DOUBLE PRECISION NOT NULL,
    "emdb_i1" DOUBLE PRECISION NOT NULL,
    "emdb_i2" DOUBLE PRECISION NOT NULL,
    "emdb_i3" DOUBLE PRECISION NOT NULL,
    "emdb_power" DOUBLE PRECISION NOT NULL,
    "emdb_meter" DOUBLE PRECISION NOT NULL,
    "emdb_in" DOUBLE PRECISION NOT NULL,
    "ups_db1" BOOLEAN NOT NULL,
    "ups_db2" BOOLEAN NOT NULL,
    "ups_db3" BOOLEAN NOT NULL,
    "ups1" BOOLEAN NOT NULL,
    "ups1_l1" DOUBLE PRECISION NOT NULL,
    "ups1_l2" DOUBLE PRECISION NOT NULL,
    "ups1_l3" DOUBLE PRECISION NOT NULL,
    "ups1_i1" DOUBLE PRECISION NOT NULL,
    "ups1_i2" DOUBLE PRECISION NOT NULL,
    "ups1_i3" DOUBLE PRECISION NOT NULL,
    "ups1_p1" DOUBLE PRECISION NOT NULL,
    "ups1_p2" DOUBLE PRECISION NOT NULL,
    "ups1_p3" DOUBLE PRECISION NOT NULL,
    "ups1_load1" DOUBLE PRECISION NOT NULL,
    "ups1_load2" DOUBLE PRECISION NOT NULL,
    "ups1_load3" DOUBLE PRECISION NOT NULL,
    "ups1_vbatt" DOUBLE PRECISION NOT NULL,
    "ups1_ibatt" DOUBLE PRECISION NOT NULL,
    "ups1_remaining" DOUBLE PRECISION NOT NULL,
    "ups2" BOOLEAN NOT NULL,
    "ups2_l1" DOUBLE PRECISION NOT NULL,
    "ups2_l2" DOUBLE PRECISION NOT NULL,
    "ups2_l3" DOUBLE PRECISION NOT NULL,
    "ups2_i1" DOUBLE PRECISION NOT NULL,
    "ups2_i2" DOUBLE PRECISION NOT NULL,
    "ups2_i3" DOUBLE PRECISION NOT NULL,
    "ups2_p1" DOUBLE PRECISION NOT NULL,
    "ups2_p2" DOUBLE PRECISION NOT NULL,
    "ups2_p3" DOUBLE PRECISION NOT NULL,
    "ups2_load1" DOUBLE PRECISION NOT NULL,
    "ups2_load2" DOUBLE PRECISION NOT NULL,
    "ups2_load3" DOUBLE PRECISION NOT NULL,
    "ups2_vbatt" DOUBLE PRECISION NOT NULL,
    "ups2_ibatt" DOUBLE PRECISION NOT NULL,
    "ups2_remaining" DOUBLE PRECISION NOT NULL,
    "ups3" BOOLEAN NOT NULL,
    "ups3_l1" DOUBLE PRECISION NOT NULL,
    "ups3_l2" DOUBLE PRECISION NOT NULL,
    "ups3_l3" DOUBLE PRECISION NOT NULL,
    "ups3_i1" DOUBLE PRECISION NOT NULL,
    "ups3_i2" DOUBLE PRECISION NOT NULL,
    "ups3_i3" DOUBLE PRECISION NOT NULL,
    "ups3_p1" DOUBLE PRECISION NOT NULL,
    "ups3_p2" DOUBLE PRECISION NOT NULL,
    "ups3_p3" DOUBLE PRECISION NOT NULL,
    "ups3_load1" DOUBLE PRECISION NOT NULL,
    "ups3_load2" DOUBLE PRECISION NOT NULL,
    "ups3_load3" DOUBLE PRECISION NOT NULL,
    "ups3_vbatt" DOUBLE PRECISION NOT NULL,
    "ups3_ibatt" DOUBLE PRECISION NOT NULL,
    "ups3_remaining" DOUBLE PRECISION NOT NULL,
    "fdc1a_status" BOOLEAN NOT NULL,
    "fdc1a_alarm" BOOLEAN NOT NULL,
    "fdc1b_status" BOOLEAN NOT NULL,
    "fdc1b_alarm" BOOLEAN NOT NULL,
    "fdc1_comment" TEXT,
    "fdc2a_status" BOOLEAN NOT NULL,
    "fdc2a_alarm" BOOLEAN NOT NULL,
    "fdc2b_status" BOOLEAN NOT NULL,
    "fdc2b_alarm" BOOLEAN NOT NULL,
    "fdc2_comment" TEXT,
    "airdb" BOOLEAN NOT NULL,
    "airdb_l1" DOUBLE PRECISION NOT NULL,
    "airdb_l2" DOUBLE PRECISION NOT NULL,
    "airdb_l3" DOUBLE PRECISION NOT NULL,
    "airdb_i1" DOUBLE PRECISION NOT NULL,
    "airdb_i2" DOUBLE PRECISION NOT NULL,
    "airdb_i3" DOUBLE PRECISION NOT NULL,
    "airdb_power" DOUBLE PRECISION NOT NULL,
    "airdb_meter" DOUBLE PRECISION NOT NULL,
    "airdb_in" DOUBLE PRECISION NOT NULL,
    "pac1" BOOLEAN NOT NULL,
    "setpoint_pac1_temp" DOUBLE PRECISION,
    "setpoint_pac1_hum" DOUBLE PRECISION,
    "return_pac1_temp" DOUBLE PRECISION,
    "return_pac1_hum" DOUBLE PRECISION,
    "pac2" BOOLEAN NOT NULL,
    "setpoint_pac2_temp" DOUBLE PRECISION,
    "setpoint_pac2_hum" DOUBLE PRECISION,
    "return_pac2_temp" DOUBLE PRECISION,
    "return_pac2_hum" DOUBLE PRECISION,
    "pac3" BOOLEAN NOT NULL,
    "setpoint_pac3_temp" DOUBLE PRECISION,
    "setpoint_pac3_hum" DOUBLE PRECISION,
    "return_pac3_temp" DOUBLE PRECISION,
    "return_pac3_hum" DOUBLE PRECISION,
    "pac4" BOOLEAN NOT NULL,
    "setpoint_pac4_temp" DOUBLE PRECISION,
    "setpoint_pac4_hum" DOUBLE PRECISION,
    "return_pac4_temp" DOUBLE PRECISION,
    "return_pac4_hum" DOUBLE PRECISION,
    "pac5" BOOLEAN NOT NULL,
    "setpoint_pac5_temp" DOUBLE PRECISION,
    "setpoint_pac5_hum" DOUBLE PRECISION,
    "return_pac5_temp" DOUBLE PRECISION,
    "return_pac5_hum" DOUBLE PRECISION,
    "pac6" BOOLEAN NOT NULL,
    "setpoint_pac6_temp" DOUBLE PRECISION,
    "setpoint_pac6_hum" DOUBLE PRECISION,
    "return_pac6_temp" DOUBLE PRECISION,
    "return_pac6_hum" DOUBLE PRECISION,
    "pac7" BOOLEAN NOT NULL,
    "setpoint_pac7_temp" DOUBLE PRECISION,
    "setpoint_pac7_hum" DOUBLE PRECISION,
    "return_pac7_temp" DOUBLE PRECISION,
    "return_pac7_hum" DOUBLE PRECISION,
    "pac8" BOOLEAN NOT NULL,
    "setpoint_pac8_temp" DOUBLE PRECISION,
    "setpoint_pac8_hum" DOUBLE PRECISION,
    "return_pac8_temp" DOUBLE PRECISION,
    "return_pac8_hum" DOUBLE PRECISION,
    "waterleak_normal" BOOLEAN NOT NULL,
    "cablefualt" BOOLEAN NOT NULL,
    "leak" BOOLEAN NOT NULL,
    "vesda" BOOLEAN NOT NULL,
    "vesda_barlevel" INTEGER NOT NULL,
    "firesystem_ac_source" BOOLEAN NOT NULL,
    "firesystem_alarmzone" BOOLEAN NOT NULL,
    "novac_u1" BOOLEAN NOT NULL,
    "novac_u2" BOOLEAN NOT NULL,
    "novac_u3" BOOLEAN NOT NULL,
    "novac_u4" BOOLEAN NOT NULL,
    "novac_u5" BOOLEAN NOT NULL,
    "tvss_pa" BOOLEAN NOT NULL,
    "tvss_pb" BOOLEAN NOT NULL,
    "tvss_pc" BOOLEAN NOT NULL,
    "cctv_playback30day" BOOLEAN NOT NULL,
    "cctv_camera" BOOLEAN NOT NULL,
    "cctv_status" BOOLEAN NOT NULL,
    "cctv_remote" BOOLEAN NOT NULL,
    "cctv_check" BOOLEAN NOT NULL,
    "ems_check" BOOLEAN NOT NULL,
    "access_control_check" BOOLEAN NOT NULL,
    "phase_check" BOOLEAN NOT NULL,
    "phase_comment" TEXT,
    "sw1_jd992a_check" BOOLEAN NOT NULL,
    "sw2_jd992a_check" BOOLEAN NOT NULL,
    "sw3_jd9663a_check" BOOLEAN NOT NULL,
    "sw4_jd9663a_check" BOOLEAN NOT NULL,
    "ems_cpu_usage" DOUBLE PRECISION NOT NULL,
    "ems_memory_usage" DOUBLE PRECISION NOT NULL,
    "ems_c_total" DOUBLE PRECISION NOT NULL,
    "ems_c_free" DOUBLE PRECISION NOT NULL,
    "ems_c_percent" DOUBLE PRECISION NOT NULL,
    "ems_d_total" DOUBLE PRECISION NOT NULL,
    "ems_d_free" DOUBLE PRECISION NOT NULL,
    "ems_d_percent" DOUBLE PRECISION NOT NULL,
    "ems_synctime" BOOLEAN NOT NULL,
    "backupvm_c_total" DOUBLE PRECISION NOT NULL,
    "backupvm_c_free" DOUBLE PRECISION NOT NULL,
    "backupvm_c_percent" DOUBLE PRECISION NOT NULL,
    "backupvm_d_total" DOUBLE PRECISION NOT NULL,
    "backupvm_d_free" DOUBLE PRECISION NOT NULL,
    "backupvm_d_percent" DOUBLE PRECISION NOT NULL,
    "backupvm_synctime" BOOLEAN NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "user_id" INTEGER NOT NULL,

    CONSTRAINT "ChecklistPhase1_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChecklistPhase2" (
    "id" SERIAL NOT NULL,
    "main_meter" DOUBLE PRECISION NOT NULL,
    "atsphase2" BOOLEAN NOT NULL,
    "atsphase2_l1" DOUBLE PRECISION NOT NULL,
    "atsphase2_l2" DOUBLE PRECISION NOT NULL,
    "atsphase2_l3" DOUBLE PRECISION NOT NULL,
    "atsphase2_i1" DOUBLE PRECISION NOT NULL,
    "atsphase2_i2" DOUBLE PRECISION NOT NULL,
    "atsphase2_i3" DOUBLE PRECISION NOT NULL,
    "atsphase2_power" DOUBLE PRECISION NOT NULL,
    "atsphase2_meter" DOUBLE PRECISION NOT NULL,
    "atsphase2_in" DOUBLE PRECISION NOT NULL,
    "emdb" BOOLEAN NOT NULL,
    "emdb_l1" DOUBLE PRECISION NOT NULL,
    "emdb_l2" DOUBLE PRECISION NOT NULL,
    "emdb_l3" DOUBLE PRECISION NOT NULL,
    "emdb_i1" DOUBLE PRECISION NOT NULL,
    "emdb_i2" DOUBLE PRECISION NOT NULL,
    "emdb_i3" DOUBLE PRECISION NOT NULL,
    "emdb_power" DOUBLE PRECISION NOT NULL,
    "emdb_meter" DOUBLE PRECISION NOT NULL,
    "emdb_in" DOUBLE PRECISION NOT NULL,
    "udb1" BOOLEAN NOT NULL,
    "udb1_l1" DOUBLE PRECISION NOT NULL,
    "udb1_l2" DOUBLE PRECISION NOT NULL,
    "udb1_l3" DOUBLE PRECISION NOT NULL,
    "udb1_i1" DOUBLE PRECISION NOT NULL,
    "udb1_i2" DOUBLE PRECISION NOT NULL,
    "udb1_i3" DOUBLE PRECISION NOT NULL,
    "udb1_power" DOUBLE PRECISION NOT NULL,
    "udb1_meter" DOUBLE PRECISION NOT NULL,
    "udb1_in" DOUBLE PRECISION NOT NULL,
    "udb2" BOOLEAN NOT NULL,
    "udb2_l1" DOUBLE PRECISION NOT NULL,
    "udb2_l2" DOUBLE PRECISION NOT NULL,
    "udb2_l3" DOUBLE PRECISION NOT NULL,
    "udb2_i1" DOUBLE PRECISION NOT NULL,
    "udb2_i2" DOUBLE PRECISION NOT NULL,
    "udb2_i3" DOUBLE PRECISION NOT NULL,
    "udb2_power" DOUBLE PRECISION NOT NULL,
    "udb2_meter" DOUBLE PRECISION NOT NULL,
    "udb2_in" DOUBLE PRECISION NOT NULL,
    "fac_inet_rst" BOOLEAN NOT NULL,
    "fac_inet_vavg" DOUBLE PRECISION NOT NULL,
    "fac_inet_iavg" DOUBLE PRECISION NOT NULL,
    "fac_inet_plot" DOUBLE PRECISION NOT NULL,
    "fac_inet_edel" DOUBLE PRECISION NOT NULL,
    "fac_thaisarn_rst" BOOLEAN NOT NULL,
    "fac_thaisarn_vavg" DOUBLE PRECISION NOT NULL,
    "fac_thaisarn_iavg" DOUBLE PRECISION NOT NULL,
    "fac_thaisarn_plot" DOUBLE PRECISION NOT NULL,
    "fac_thaisarn_edel" DOUBLE PRECISION NOT NULL,
    "ups1" BOOLEAN NOT NULL,
    "ups1_l1" DOUBLE PRECISION NOT NULL,
    "ups1_l2" DOUBLE PRECISION NOT NULL,
    "ups1_l3" DOUBLE PRECISION NOT NULL,
    "ups1_i1" DOUBLE PRECISION NOT NULL,
    "ups1_i2" DOUBLE PRECISION NOT NULL,
    "ups1_i3" DOUBLE PRECISION NOT NULL,
    "ups1_p1" DOUBLE PRECISION NOT NULL,
    "ups1_p2" DOUBLE PRECISION NOT NULL,
    "ups1_p3" DOUBLE PRECISION NOT NULL,
    "ups1_load1" DOUBLE PRECISION NOT NULL,
    "ups1_load2" DOUBLE PRECISION NOT NULL,
    "ups1_load3" DOUBLE PRECISION NOT NULL,
    "ups1_vbatt" DOUBLE PRECISION NOT NULL,
    "ups1_ibatt" DOUBLE PRECISION NOT NULL,
    "ups1_remaining" DOUBLE PRECISION NOT NULL,
    "ups2" BOOLEAN NOT NULL,
    "ups2_l1" DOUBLE PRECISION NOT NULL,
    "ups2_l2" DOUBLE PRECISION NOT NULL,
    "ups2_l3" DOUBLE PRECISION NOT NULL,
    "ups2_i1" DOUBLE PRECISION NOT NULL,
    "ups2_i2" DOUBLE PRECISION NOT NULL,
    "ups2_i3" DOUBLE PRECISION NOT NULL,
    "ups2_p1" DOUBLE PRECISION NOT NULL,
    "ups2_p2" DOUBLE PRECISION NOT NULL,
    "ups2_p3" DOUBLE PRECISION NOT NULL,
    "ups2_load1" DOUBLE PRECISION NOT NULL,
    "ups2_load2" DOUBLE PRECISION NOT NULL,
    "ups2_load3" DOUBLE PRECISION NOT NULL,
    "ups2_vbatt" DOUBLE PRECISION NOT NULL,
    "ups2_ibatt" DOUBLE PRECISION NOT NULL,
    "ups2_remaining" DOUBLE PRECISION NOT NULL,
    "ups3" BOOLEAN NOT NULL,
    "ups3_l1" DOUBLE PRECISION NOT NULL,
    "ups3_l2" DOUBLE PRECISION NOT NULL,
    "ups3_l3" DOUBLE PRECISION NOT NULL,
    "ups3_i1" DOUBLE PRECISION NOT NULL,
    "ups3_i2" DOUBLE PRECISION NOT NULL,
    "ups3_i3" DOUBLE PRECISION NOT NULL,
    "ups3_p1" DOUBLE PRECISION NOT NULL,
    "ups3_p2" DOUBLE PRECISION NOT NULL,
    "ups3_p3" DOUBLE PRECISION NOT NULL,
    "ups3_load1" DOUBLE PRECISION NOT NULL,
    "ups3_load2" DOUBLE PRECISION NOT NULL,
    "ups3_load3" DOUBLE PRECISION NOT NULL,
    "ups3_vbatt" DOUBLE PRECISION NOT NULL,
    "ups3_ibatt" DOUBLE PRECISION NOT NULL,
    "ups3_remaining" DOUBLE PRECISION NOT NULL,
    "fdc1a_status" BOOLEAN NOT NULL,
    "fdc1a_alarm" BOOLEAN NOT NULL,
    "fdc1b_status" BOOLEAN NOT NULL,
    "fdc1b_alarm" BOOLEAN NOT NULL,
    "fdc1_comment" TEXT,
    "fdc2a_status" BOOLEAN NOT NULL,
    "fdc2a_alarm" BOOLEAN NOT NULL,
    "fdc2b_status" BOOLEAN NOT NULL,
    "fdc2b_alarm" BOOLEAN NOT NULL,
    "fdc2_comment" TEXT,
    "airdb" BOOLEAN NOT NULL,
    "airdb_l1" DOUBLE PRECISION NOT NULL,
    "airdb_l2" DOUBLE PRECISION NOT NULL,
    "airdb_l3" DOUBLE PRECISION NOT NULL,
    "airdb_i1" DOUBLE PRECISION NOT NULL,
    "airdb_i2" DOUBLE PRECISION NOT NULL,
    "airdb_i3" DOUBLE PRECISION NOT NULL,
    "airdb_power" DOUBLE PRECISION NOT NULL,
    "airdb_meter" DOUBLE PRECISION NOT NULL,
    "airdb_in" DOUBLE PRECISION NOT NULL,
    "pac1" BOOLEAN NOT NULL,
    "setpoint_pac1_temp" DOUBLE PRECISION,
    "setpoint_pac1_hum" DOUBLE PRECISION,
    "return_pac1_temp" DOUBLE PRECISION,
    "return_pac1_hum" DOUBLE PRECISION,
    "pac2" BOOLEAN NOT NULL,
    "setpoint_pac2_temp" DOUBLE PRECISION,
    "setpoint_pac2_hum" DOUBLE PRECISION,
    "return_pac2_temp" DOUBLE PRECISION,
    "return_pac2_hum" DOUBLE PRECISION,
    "pac3" BOOLEAN NOT NULL,
    "setpoint_pac3_temp" DOUBLE PRECISION,
    "setpoint_pac3_hum" DOUBLE PRECISION,
    "return_pac3_temp" DOUBLE PRECISION,
    "return_pac3_hum" DOUBLE PRECISION,
    "pac4" BOOLEAN NOT NULL,
    "setpoint_pac4_temp" DOUBLE PRECISION,
    "setpoint_pac4_hum" DOUBLE PRECISION,
    "return_pac4_temp" DOUBLE PRECISION,
    "return_pac4_hum" DOUBLE PRECISION,
    "pac5" BOOLEAN NOT NULL,
    "setpoint_pac5_temp" DOUBLE PRECISION,
    "setpoint_pac5_hum" DOUBLE PRECISION,
    "return_pac5_temp" DOUBLE PRECISION,
    "return_pac5_hum" DOUBLE PRECISION,
    "pac6" BOOLEAN NOT NULL,
    "setpoint_pac6_temp" DOUBLE PRECISION,
    "setpoint_pac6_hum" DOUBLE PRECISION,
    "return_pac6_temp" DOUBLE PRECISION,
    "return_pac6_hum" DOUBLE PRECISION,
    "pac7" BOOLEAN NOT NULL,
    "setpoint_pac7_temp" DOUBLE PRECISION,
    "setpoint_pac7_hum" DOUBLE PRECISION,
    "return_pac7_temp" DOUBLE PRECISION,
    "return_pac7_hum" DOUBLE PRECISION,
    "pac8" BOOLEAN NOT NULL,
    "setpoint_pac8_temp" DOUBLE PRECISION,
    "setpoint_pac8_hum" DOUBLE PRECISION,
    "return_pac8_temp" DOUBLE PRECISION,
    "return_pac8_hum" DOUBLE PRECISION,
    "waterleak_normal" BOOLEAN NOT NULL,
    "cablefualt" BOOLEAN NOT NULL,
    "leak" BOOLEAN NOT NULL,
    "vesda" BOOLEAN NOT NULL,
    "vesda_barlevel" INTEGER NOT NULL,
    "firesystem_ac_source" BOOLEAN NOT NULL,
    "firesystem_alarmzone" BOOLEAN NOT NULL,
    "novac_u1" BOOLEAN NOT NULL,
    "novac_u2" BOOLEAN NOT NULL,
    "novac_u3" BOOLEAN NOT NULL,
    "novac_u4" BOOLEAN NOT NULL,
    "novac_u5" BOOLEAN NOT NULL,
    "tvss_pa" BOOLEAN NOT NULL,
    "tvss_pb" BOOLEAN NOT NULL,
    "tvss_pc" BOOLEAN NOT NULL,
    "cctv_playback30day" BOOLEAN NOT NULL,
    "cctv_camera" BOOLEAN NOT NULL,
    "cctv_status" BOOLEAN NOT NULL,
    "cctv_remote" BOOLEAN NOT NULL,
    "cctv_check" BOOLEAN NOT NULL,
    "ems_check" BOOLEAN NOT NULL,
    "access_control_check" BOOLEAN NOT NULL,
    "phase_check" BOOLEAN NOT NULL,
    "phase_comment" TEXT,
    "sw1_jd992a_check" BOOLEAN NOT NULL,
    "sw2_jd992a_check" BOOLEAN NOT NULL,
    "sw3_jd9663a_check" BOOLEAN NOT NULL,
    "sw4_jd9663a_check" BOOLEAN NOT NULL,
    "ems_cpu_usage" DOUBLE PRECISION NOT NULL,
    "ems_memory_usage" DOUBLE PRECISION NOT NULL,
    "ems_c_total" DOUBLE PRECISION NOT NULL,
    "ems_c_free" DOUBLE PRECISION NOT NULL,
    "ems_c_percent" DOUBLE PRECISION NOT NULL,
    "ems_d_total" DOUBLE PRECISION NOT NULL,
    "ems_d_free" DOUBLE PRECISION NOT NULL,
    "ems_d_percent" DOUBLE PRECISION NOT NULL,
    "ems_synctime" BOOLEAN NOT NULL,
    "backupvm_c_total" DOUBLE PRECISION NOT NULL,
    "backupvm_c_free" DOUBLE PRECISION NOT NULL,
    "backupvm_c_percent" DOUBLE PRECISION NOT NULL,
    "backupvm_d_total" DOUBLE PRECISION NOT NULL,
    "backupvm_d_free" DOUBLE PRECISION NOT NULL,
    "backupvm_d_percent" DOUBLE PRECISION NOT NULL,
    "backupvm_synctime" BOOLEAN NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "user_id" INTEGER NOT NULL,

    CONSTRAINT "ChecklistPhase2_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChecklistRoomTemp" (
    "id" SERIAL NOT NULL,
    "TempDetector_1_temp" DOUBLE PRECISION,
    "TempDetector_1_hum" DOUBLE PRECISION,
    "TempDetector_2_temp" DOUBLE PRECISION,
    "TempDetector_2_hum" DOUBLE PRECISION,
    "TempDetector_3_temp" DOUBLE PRECISION,
    "TempDetector_3_hum" DOUBLE PRECISION,
    "TempDetector_4_temp" DOUBLE PRECISION,
    "TempDetector_4_hum" DOUBLE PRECISION,
    "TempDetector_5_temp" DOUBLE PRECISION,
    "TempDetector_5_hum" DOUBLE PRECISION,
    "TempDetector_6_temp" DOUBLE PRECISION,
    "TempDetector_6_hum" DOUBLE PRECISION,
    "TempDetector_7_temp" DOUBLE PRECISION,
    "TempDetector_7_hum" DOUBLE PRECISION,
    "TempDetector_8_temp" DOUBLE PRECISION,
    "TempDetector_8_hum" DOUBLE PRECISION,
    "TempDetector_9_temp" DOUBLE PRECISION,
    "TempDetector_9_hum" DOUBLE PRECISION,
    "TempDetector_10_temp" DOUBLE PRECISION,
    "TempDetector_10_hum" DOUBLE PRECISION,
    "TempDetector_11_temp" DOUBLE PRECISION,
    "TempDetector_11_hum" DOUBLE PRECISION,
    "TempDetector_12_temp" DOUBLE PRECISION,
    "TempDetector_12_hum" DOUBLE PRECISION,
    "TempDetector_13_temp" DOUBLE PRECISION,
    "TempDetector_13_hum" DOUBLE PRECISION,
    "TempDetector_14_temp" DOUBLE PRECISION,
    "TempDetector_14_hum" DOUBLE PRECISION,
    "TempDetector_15_temp" DOUBLE PRECISION,
    "TempDetector_15_hum" DOUBLE PRECISION,
    "TempDetector_16_temp" DOUBLE PRECISION,
    "TempDetector_16_hum" DOUBLE PRECISION,
    "TempDetector_17_temp" DOUBLE PRECISION,
    "TempDetector_17_hum" DOUBLE PRECISION,
    "TempDetector_18_temp" DOUBLE PRECISION,
    "TempDetector_18_hum" DOUBLE PRECISION,
    "TempDetector_19_temp" DOUBLE PRECISION,
    "TempDetector_19_hum" DOUBLE PRECISION,
    "TempDetector_20_temp" DOUBLE PRECISION,
    "TempDetector_20_hum" DOUBLE PRECISION,
    "TempDetector_21_temp" DOUBLE PRECISION,
    "TempDetector_21_hum" DOUBLE PRECISION,
    "TempDetector_22_temp" DOUBLE PRECISION,
    "TempDetector_22_hum" DOUBLE PRECISION,
    "TempDetector_23_temp" DOUBLE PRECISION,
    "TempDetector_23_hum" DOUBLE PRECISION,
    "TempDetector_24_temp" DOUBLE PRECISION,
    "TempDetector_24_hum" DOUBLE PRECISION,
    "phase1" BOOLEAN NOT NULL,
    "phase2" BOOLEAN NOT NULL,
    "Alart" TEXT,
    "outside_temp" DOUBLE PRECISION NOT NULL,
    "outside_hum" DOUBLE PRECISION NOT NULL,
    "tr_room_temp" DOUBLE PRECISION NOT NULL,
    "tr_room_hum" DOUBLE PRECISION NOT NULL,
    "tr_ch1" DOUBLE PRECISION NOT NULL,
    "tr_ch2" DOUBLE PRECISION NOT NULL,
    "tr_ch3" DOUBLE PRECISION NOT NULL,
    "fan1" BOOLEAN,
    "fan2" BOOLEAN,
    "fan3" BOOLEAN,
    "fan4" BOOLEAN,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "user_id" INTEGER NOT NULL,

    CONSTRAINT "ChecklistRoomTemp_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChecklistFdc" (
    "id" SERIAL NOT NULL,
    "fdc_phase1" DOUBLE PRECISION NOT NULL,
    "fdc_phase2" DOUBLE PRECISION NOT NULL,
    "fdc_comment" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "user_id" INTEGER NOT NULL,

    CONSTRAINT "ChecklistFdc_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "checklistTransformer" (
    "id" SERIAL NOT NULL,
    "sw_in1" BOOLEAN NOT NULL,
    "sw_ground_in1" BOOLEAN NOT NULL,
    "lamp_rmu_in1" BOOLEAN NOT NULL,
    "sw_in1_comment" TEXT,
    "sw_in2" BOOLEAN NOT NULL,
    "sw_ground_in2" BOOLEAN NOT NULL,
    "lamp_rmu_in2" BOOLEAN NOT NULL,
    "sw_in2_comment" TEXT,
    "sw1_out1" BOOLEAN NOT NULL,
    "sw2_out1" BOOLEAN NOT NULL,
    "sw_ground_out1" BOOLEAN NOT NULL,
    "lamp_rmu_out1" BOOLEAN NOT NULL,
    "sw_out1_comment" TEXT,
    "sw1_out2" BOOLEAN NOT NULL,
    "sw2_out2" BOOLEAN NOT NULL,
    "sw_ground_out2" BOOLEAN NOT NULL,
    "lamp_rmu_out2" BOOLEAN NOT NULL,
    "sw_out2_comment" TEXT,
    "pressure" BOOLEAN NOT NULL,
    "tr_ch1" DOUBLE PRECISION NOT NULL,
    "tr_ch2" DOUBLE PRECISION NOT NULL,
    "tr_ch3" DOUBLE PRECISION NOT NULL,
    "tr_room_temp" DOUBLE PRECISION NOT NULL,
    "tr_room_hum" DOUBLE PRECISION NOT NULL,
    "tr_temp_comment" TEXT,
    "fan_status" BOOLEAN,
    "tr_temp_alarm" BOOLEAN NOT NULL,
    "tr_temp_trip" BOOLEAN NOT NULL,
    "fan_tr_comment" TEXT,
    "meter" DOUBLE PRECISION NOT NULL,
    "l1" DOUBLE PRECISION NOT NULL,
    "l2" DOUBLE PRECISION NOT NULL,
    "l3" DOUBLE PRECISION NOT NULL,
    "i1" DOUBLE PRECISION NOT NULL,
    "i2" DOUBLE PRECISION NOT NULL,
    "i3" DOUBLE PRECISION NOT NULL,
    "pf" DOUBLE PRECISION NOT NULL,
    "main_mcb" BOOLEAN NOT NULL,
    "db1" BOOLEAN NOT NULL,
    "db2" BOOLEAN NOT NULL,
    "mcb1" BOOLEAN NOT NULL,
    "mcb2" BOOLEAN NOT NULL,
    "capbank" BOOLEAN NOT NULL,
    "status_capbank" BOOLEAN NOT NULL,
    "mode_fan" BOOLEAN NOT NULL,
    "fan1" BOOLEAN,
    "fan2" BOOLEAN,
    "fan3" BOOLEAN,
    "fan4" BOOLEAN,
    "fan_ver_comment" TEXT,
    "meter_TOU" DOUBLE PRECISION NOT NULL,
    "onpeak" DOUBLE PRECISION NOT NULL,
    "offpeak" DOUBLE PRECISION NOT NULL,
    "all_onpeak" DOUBLE PRECISION NOT NULL,
    "all_offpeak" DOUBLE PRECISION NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "user_id" INTEGER NOT NULL,

    CONSTRAINT "checklistTransformer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChecklistGenerator" (
    "id" SERIAL NOT NULL,
    "generator_name" TEXT NOT NULL,
    "ats_meter_unit" DOUBLE PRECISION,
    "around_check" BOOLEAN,
    "batt_check" BOOLEAN,
    "batt_connection_check" BOOLEAN,
    "volt_batt_check" DOUBLE PRECISION,
    "fuel_value_check" DOUBLE PRECISION,
    "fuel_leak_check" BOOLEAN,
    "oil_value_check" BOOLEAN,
    "oil_leak_check" BOOLEAN,
    "cooler_check" BOOLEAN,
    "filter_cooler_check" BOOLEAN,
    "fan_cooler_check" BOOLEAN,
    "cooler_leak_check" BOOLEAN,
    "airduct_check" BOOLEAN,
    "airfilter_condition_check" BOOLEAN,
    "electic_junction_check" BOOLEAN,
    "electic_insulation_check" BOOLEAN,
    "ground_check" BOOLEAN,
    "electic_panel_check" BOOLEAN,
    "time_start" TIMESTAMP(3),
    "engine_check" BOOLEAN,
    "afterstart_junction_check" BOOLEAN,
    "afterstart_insulation_check" BOOLEAN,
    "l1" DOUBLE PRECISION,
    "l2" DOUBLE PRECISION,
    "l3" DOUBLE PRECISION,
    "i1" DOUBLE PRECISION,
    "i2" DOUBLE PRECISION,
    "i3" DOUBLE PRECISION,
    "frequency" DOUBLE PRECISION,
    "rpm" DOUBLE PRECISION,
    "voltbatt" DOUBLE PRECISION,
    "enginetemp" DOUBLE PRECISION,
    "cooldown" DOUBLE PRECISION,
    "comment" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "user_id" INTEGER NOT NULL,

    CONSTRAINT "ChecklistGenerator_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Users_username_key" ON "Users"("username");

-- AddForeignKey
ALTER TABLE "Company" ADD CONSTRAINT "Company_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "Teams"("team_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Members" ADD CONSTRAINT "Members_comp_id_fkey" FOREIGN KEY ("comp_id") REFERENCES "Company"("comp_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChecklistPhase1" ADD CONSTRAINT "ChecklistPhase1_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "Users"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChecklistPhase2" ADD CONSTRAINT "ChecklistPhase2_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "Users"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChecklistRoomTemp" ADD CONSTRAINT "ChecklistRoomTemp_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "Users"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChecklistFdc" ADD CONSTRAINT "ChecklistFdc_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "Users"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "checklistTransformer" ADD CONSTRAINT "checklistTransformer_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "Users"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChecklistGenerator" ADD CONSTRAINT "ChecklistGenerator_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "Users"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;
